### PR TITLE
[WIP] Use alternative fallback method in `outboundLinkTracker`

### PR DESCRIPTION
**Pull request by MethodGrab**
PR for #89.

I've added the functionality but I'm having trouble getting selenium running locally (Windows) to update the tests, hence the WIP tag.

### CODE REVIEW

**Comment by MethodGrab** [comment]
Hmm, this is harder to test than I thought.
In order to validate the `hitData`, the redirect with `window.location` needs to be mocked/stubbed to prevent the page changing.

**Comment by philipwalton** [comment]
Were you able to get the tests running on windows? If the testing part is too much of a pain, I'm happy to merge your WIP changes into a branch on the autotrack repo, and then merge to master myself once I get the tests working.

The initial release version of autotrack had a `sessionDurationTracker` plugin (since removed) with a similar testing challenge -- it required testing that a navigation to a new page was successful. The solution I used looked something like this:

- Create a parent page to host the test page in an `<iframe>`.
- Update the `sendHitTask` logic to `postMessage` to the parent frame instead of populating the local `hitData` object.
- In the parent frame, ensure the navigation happened and the proper `hitData` was sent.

Again, I'm happy to do this part if the testing becomes too much of a pain. If you want to PR to a branch, let me know and I'll create a new one.

**Comment by MethodGrab** [comment]
No, unfortunately I still cant run selenium. If you're happy to accept the PR on a branch then I think that would be best!

**Comment by philipwalton** [comment]
Continued in #91.

**Pull request closed without merging**
