### PR TITLE
Add new maxScrollTracker plugin

### PR DESCRIPTION
**Pull request by eduardocereto**

### CODE REVIEW

**Comment by eduardocereto** [comment]
Should add the necessary tests by next week

**Comment by philipwalton** [comment]
Hey @eduardocereto, can you rebase these changes against the [1.0-dev](https://github.com/googleanalytics/autotrack/tree/1.0-dev) branch and either update this PR or create a new one to merge into 1.0-dev instead of master?

See #67 for details and version 1.0 progress.

**Comment by eduardocereto** [comment]
Of course, any idea on release date plans for 1.0?

**Comment by eduardocereto** [comment]
I'll close this for now and reopen after I rebase.

**Comment by philipwalton** [comment]
Probably sometime this month. Most of the features have already been implemented.

**Pull request closed without merging**
