### PR TITLE
Add new WIP outboundLinkTracker fallback logic

### PR DESCRIPTION
**Pull request by philipwalton**
Continued from #90.

### CODE REVIEW

**Comment by philipwalton** [comment]
Thanks @MethodGrab! Merged.

**Comment by philipwalton** [comment]
@MethodGrab please confirm you're OK with this merge to appease @googlebot :)

**Comment by MethodGrab** [comment]
Sorry, I've only just seen this!
@googlebot :+1: approved!

**Comment by philipwalton** [comment]
When I updated the test infrastructure, I added this code to make this change, but I realized it's a bit more complicated than what's in this PR. The problem is if some other code calls `event.preventDefault()`, you wouldn't want to load the new page, but if your event handler runs before the event handler that calls `event.preventDefault()`, it's tricky to stop it.

The solution was to add a new event handler on `window` whenever an outbound click is detected, and then in that handler check for `event.defaultPrevented`.

This change has been merged, you can check out the code here:
https://github.com/googleanalytics/autotrack/blob/79eea78310276fd5860e3a50d01540452e09068c/lib/plugins/outbound-link-tracker.js#L84-L100

**Pull request merged**
