### PR TITLE
Chinese Translation Submit

### PR DESCRIPTION
**Pull request by stevezhuang**
Hi there

This is the autotrack Chinese simplified translation, the link you can kindly refer to [https://github.com/stevezhuang/autotrack/blob/master/README.zh.md](https://github.com/stevezhuang/autotrack/blob/master/README.zh.md).

I just committed and hope this can work well for the pull request.

For the further modification, I am going to review them every now and then and make sure they can be up-to-date as well as more accuracy. 

Please let me know if any. Thanks!

Thanks,
Steve.

### CODE REVIEW

**Comment by stevezhuang** [comment]
Hi  I signed it! Please check it out.

**Comment by stevezhuang** [comment]
ok, thank you. looks like the checks were not successful.

**Comment by philipwalton** [comment]
Thanks, I'm happy to link to this, but for the pull request you just need to include the changes to the README file. As it is now, this pull request would delete all the files in the repo, so I can't merge it as is.

**Comment by stevezhuang** [comment]
Thanks for the feedback, I tried another pull by https://github.com/googleanalytics/autotrack/pull/77. It was a single pull request for the README.md file, I hope it can work. Please let me know if it is doable for the merge.

**Comment by philipwalton** [comment]
Thanks, I merged #77.

**Pull request closed without merging**
