### PR TITLE
fix check of the property name of a dimension

### PR DESCRIPTION
**Pull request by floriangosse**

### CODE REVIEW

**Comment by philipwalton** [comment]
Thanks for catching this. I just realized that `analytics.js` initializes plugins inside of a try/catch block, so turns out these errors are never actually being thrown.

Can you update your code changes to be something like this?

```js
if (!dimension.name || !dimension.dimensionIndex) return;
```

If not, I can do it.

**Comment by philipwalton** [comment]
I've included these changes in #42.

**Comment by floriangosse** [comment]
Thank you. I was a little busy the days. :-)

**Comment by philipwalton** [comment]
Not a problem! Thanks for finding the issue.

**Pull request closed without merging**
