### PR TITLE
added README.ja.md, japanese translation

### PR DESCRIPTION
**Pull request by nebosuker**
This is my 1st time using Github pull request, so please forgive me if there's anything strange or rude.

I made Japanese version of README.md. If it helps, please include it for Japanese GA users : )

Thanks.

### CODE REVIEW

**Comment by nebosuker** [comment]
Thanks @philipwalton 

How about W3C style translation link?

[https://www.w3.org/TR/html5/](https://www.w3.org/TR/html5/)
[https://www.w3.org/TR/2013/REC-css-style-attr-20131107/](https://www.w3.org/TR/2013/REC-css-style-attr-20131107/)

Those drafts have "See also translations." link at the header section and the link points to an index page that leads to each translations.

You can put "These are unofficial documents:" notice there.

And, putting "checked" icon to the links to the document that Google Analytics team of corresponding country has checked validity might be a good idea.

**Comment by philipwalton** [comment]
I think the best option given our team's time and resources is to add a section to the README called "translations" which would contain a list of forks with the translated docs. The forks could be of the entire repo or just the README.md file, I don't have a strong preference.

Contributors can submit a PR to have their fork listed in the official repo, and then it'll be on them to keep it as up-to-date as possible.

How does that sound? Can you update your PR? Or if you want I can do it, and just link to your repo.

**Comment by nebosuker** [comment]
It should be fine, I guess.

As to 

> Can you update your PR?

I couldn't grasp what to do... sorry about my poor English understanding.
Would you please do it ?

**Comment by philipwalton** [comment]
I can update the README with the translation section.

Can you update [your fork of autotrack](https://github.com/nebosuker/autotrack) to only include the Japanese version of the README.md file? In other words, remove all the files other than README.ja.md so there aren't conflicting versions.

Once your fork is updated, I'll link to it.

**Comment by nebosuker** [comment]
Thanks Philip, I now know what to do, and done!

**Comment by philipwalton** [comment]
Closed via #29.

**Pull request closed without merging**
