### PR TITLE
Add support for defining eventValue in the outboundLinkTracker

### PR DESCRIPTION
**Pull request by Edubits**
The implementation is done to mirror the same attributes as used for eventTracker.

### CODE REVIEW

**Comment by Edubits** [comment]
I signed it!

Op vr 13 mei 2016 om 12:19 schreef googlebot <notifications@github.com>:

**Comment by Edubits** [comment]
Check

**Comment by philipwalton** [comment]
Thanks @Edubits, looks like we were both thinking about this at around the same time.

This feature is currently possible using the code from the v1 branch. And in v1 it works in a way that's generalized to support declarative attribute overrides for any analytics fields and works with any plugin that sends hits as a result of user interactions.

You can see the changes for that feature in #74, and you can follow along with all v1 development in #67 if you want to see what new features autotrack will support.

**Comment by Edubits** [comment]
@philipwalton Awesome! I totally missed #67, but I'm glad to see you _just_ implemented the feature I was looking for in #74, looks good!

**Pull request closed without merging**
